FROM node:lts-alpine AS builder
WORKDIR /app
COPY *.json .
COPY *.html .
COPY *.ts .
RUN npm install
RUN npm install -g typescript
COPY src/ .
RUN tsc

FROM node:lts-alpine
RUN apk --no-cache add curl
WORKDIR /app
COPY --from=builder /app/build .
COPY package*.json .
RUN npm install --production
CMD ["npm", "run", "start"]