FROM node:lts-alpine

WORKDIR /app
ENV CHOKIDAR_USEPOLLING=true

RUN apk --no-cache add curl

COPY package*.json ./
COPY tsconfig* ./
COPY codegen.ts ./

RUN npm install --legacy-peer-deps

COPY public ./public
COPY src ./src
COPY index.html ./

# COPY components.json ./
COPY *.config.ts ./
COPY *.config.js ./

CMD ["npm", "run", "dev"]
