x-baseService: &baseService
  restart: always
  healthcheck:
    interval: 10s
    timeout: 5s
    retries: 5
    start_period: 30s
    start_interval: 10s

services:
  gateway-dev:
    <<: *baseService
    container_name: gateway-dev
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - ${GATEWAY_PORT}:80
    depends_on:
      backend-dev:
        condition: service_healthy
      files-dev:
        condition: service_healthy
      frontend-dev:
        condition: service_healthy
      adminer-dev:
        condition: service_started
    environment:
      BACKEND_PORT: ${BACKEND_PORT}

  database-dev:
    <<: *baseService
    container_name: database-dev
    image: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d ${DB_SCHEMA} -U ${DB_USER}']
    volumes:
      - ./persist/database-dev/:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}

  adminer-dev:
    <<: *baseService
    container_name: adminer-dev
    image: adminer
    depends_on:
      database-dev:
        condition: service_healthy

  backend-dev:
    <<: *baseService
    container_name: backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -m 5 --fail --request POST --header ''Content-Type: application/json'' --url ''http://backend-dev:4005'' --data ''{"query":"query { __typename }"}'' || exit 1',
        ]
    volumes:
      - ./backend/src:/app/src/
      - ./persist/backend-dev:/app/static
    depends_on:
      database-dev:
        condition: service_healthy
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      BACKEND_PORT: ${BACKEND_PORT}
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_TTL: ${COOKIE_TTL}
      GOOGLE_APP_PASSWORD: ${GOOGLE_APP_PASSWORD}
      GOOGLE_APP_EMAIL: ${GOOGLE_APP_EMAIL}

  files-dev:
    <<: *baseService
    container_name: files-dev
    build:
      context: ./files
      dockerfile: Dockerfile.dev
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "curl -m 5 --fail --request GET --url 'http://files-dev:4000/health'|| exit 1",
        ]
    volumes:
      - ./files/src:/app/src/
      - ./persist/files-dev:/app/public

  frontend-dev:
    <<: *baseService
    container_name: frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "curl -m 5 --fail --request GET --url 'http://frontend-dev:5173'|| exit 1",
        ]
    volumes:
      - ./frontend/src/:/app/src/
    environment:
      VITE_GATEWAY_PORT: ${GATEWAY_PORT}
      VITE_WS_URL: ${VITE_WS_URL}
      VITE_API_URL: ${VITE_API_URL}
