services:
  backend:
    depends_on:
      - database-eco
    container_name: backend-eco
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_SERVER_IMAGE_NAME}:latest
    volumes:
      - ./backend/src/:/app/src/
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      BACKEND_PORT: ${BACKEND_PORT}

  files:
    container_name: files-eco
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_FILES_IMAGE_NAME}:latest
    volumes:
      - ./files/src:/app/src/
      - ./persist/files-dev:/app/public

  frontend:
    depends_on:
      - backend
      - files
    container_name: frontend-eco
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_CLIENT_IMAGE_NAME}:latest
    volumes:
      - ./frontend/src/:/app/src/
    environment:
      VITE_GATEWAY_PORT: ${GATEWAY_PORT}

  database-eco:
    container_name: database-eco
    image: postgres
    volumes:
      - ./persist/data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}

  gateway:
    depends_on:
      - frontend
      - backend
      - database-eco
      - files
    container_name: gateway-eco
    image: nginx
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/dev.conf.template
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
    command: /bin/bash -c "envsubst '$$BACKEND_PORT' < /etc/nginx/conf.d/dev.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
