events {}

http {
    server {
        listen 80;

        location /api {
            proxy_pass http://backend-e2e:4005;
        }

        location /files {
            proxy_pass http://files-e2e:4000;
        }
        
        location /hmr {
            proxy_pass http://frontend-e2e:7000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # location /playwright {
        #     proxy_pass http://playwright-e2e:9323;
        # }

        location / {
            proxy_pass http://frontend-e2e:5173;
        }
    }
}
