FROM node:lts-alpine
RUN mkdir /app
WORKDIR /app
RUN apk --no-cache add curl
COPY package*.json ./
COPY tsconfig.json tsconfig.json
COPY nodemon.json nodemon.json
RUN npm i
RUN npm i -D nodemon ts-node concurrently
COPY src src
CMD ["npm", "run", "dev"]
