name: test

on:
  pull_request:
    branches:
      - dev
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - frontend
          - backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: 'npm'

      - name: Filter changed files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

      - name: Run tests
        if: ${{ steps.filter.outputs[matrix.service] == 'true' }}
        run: |
          cd ${{ matrix.service }}
          npm ci --ignore-scripts
          npm run test
